### ISSUE TITLE
Add Category ID Metadata

### ISSUE THREAD

**Issue by HassanAbouelela** [MrHemlock/auto_guild#6]
Currently, categories do not include their IDs in the end result, making it more difficult to use and might require users to manually add them at the end. I'm proposing the following modification to the current format:

```yaml
categories:
  super_secret:
    - id: number
    - channel: text
```

In this case, `id` should be a reserved keyword used specifically for the category IDs.
